- name: Instalar dependências do Docker
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Adicionar chave GPG do Docker
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Adicionar repositório Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Instalar Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Adicionar usuário ao grupo docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
