---
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: true

- name: Configure Git user name
  git_config:
    name: user.name
    value: "{{ ansible_user }}"
    scope: global

- name: Configure Git user email
  git_config:
    name: user.email
    value: "{{ user_email }}"
    scope: global

- name: Configure default branch to main
  git_config:
    name: init.defaultBranch
    value: main
    scope: global

- name: Check if SSH key exists
  stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  register: ssh_key_check

- name: Generate SSH key if not exists
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ user_email }}"
    force: false
    mode: "0600"
  when: not ssh_key_check.stat.exists

- name: Ensure ssh-agent is running and key is added
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519
  args:
    executable: /bin/bash

- name: Show public SSH key
  shell: cat {{ ansible_env.HOME }}/.ssh/id_ed25519.pub
  register: ssh_key_output

- name: Display public SSH key to add to GitHub
  debug:
    msg: "{{ ssh_key_output.stdout }}"
